
# tap repositories and their packages

## caskroom/cask
tap caskroom/cask
brew brew-cask
cask adobe-air
cask alfred
cask amazon-cloud-drive
cask android-studio
cask appcleaner
cask atom
cask bittorrent-sync
cask brackets
cask chefdk
cask coteditor
cask dropbox
cask github-desktop
cask gmvault
cask google-drive
cask google-earth
cask google-web-designer
cask handbrake
cask haskell-platform
cask imagealpha
cask imageoptim
cask iterm2
cask java
cask karabiner
cask libreoffice
cask mactex
cask mendeley-desktop
cask miro-video-converter
cask omnigraffle
cask omnioutliner
cask omnipresence
cask opera
cask processing
cask scrivener
cask send-to-kindle
cask skype
cask sourcetree
cask textmate
cask transmit
cask vagrant
cask virtualbox
cask visual-studio-code
cask vivaldi
cask vlc
cask xquartz

## caskroom/versions
tap caskroom/versions
cask firefox-ja
cask firefoxdeveloperedition-ja
cask sublime-text-dev

## homebrew/dupes
tap homebrew/dupes

## homebrew/php
tap homebrew/php
brew boris
brew php55-mailparse
brew php55-mcrypt
brew php55-xdebug
brew php55
brew phpcpd
brew phploc
brew phpmd
brew phpunit

## homebrew/versions
tap homebrew/versions
brew perl516

## peco/peco
tap peco/peco
brew peco

## rcmdnk/file
tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew aspcud
brew autoconf
brew automake
brew cairo
brew camlp4
brew chromedriver
brew clasp
brew clisp
brew clojurescript
brew cloog
brew cmake
brew composer
brew dirmngr
brew elixir
brew erlang
brew faac
brew ffmpeg
brew fontconfig
brew freetype
brew gauche
brew gcc
brew gdb
brew gdbm
brew gettext
brew giflib
brew gist
brew git
brew git-flow
brew glib
brew global
brew gmp
brew gnupg2
brew go
brew gpg-agent
brew gringo
brew hg-flow
brew icu4c
brew imagemagick
brew ios-sim
brew isl
brew jpeg
brew julius
brew lame
brew leiningen
brew lftp
brew libassuan
brew libffi
brew libgcrypt
brew libgpg-error
brew libksba
brew libmpc
brew libpng
brew libsigsegv
brew libtiff
brew libtool
brew libusb
brew libusb-compat
brew libvo-aacenc
brew libxml2
brew libyaml
brew lv
brew mackup
brew mcrypt
brew mecab
brew mecab-ipadic
brew mercurial
brew mhash
brew mongodb
brew mpfr
brew mysql
brew nkf
brew objective-caml
brew ocaml
brew opam
brew open-sp
brew openssl
brew ossp-uuid
brew p7zip
brew pandoc
brew pcre
brew phpunit-skeleton-generator
brew pinentry
brew pixman
brew pkg-config
brew postgresql
brew potrace
brew pth
brew pwgen
brew pyside
brew python
brew qt
brew rbenv
brew readline
brew ruby-build
brew sbt
brew scala
brew selenium-server-standalone
brew shiboken
brew smlnj
brew sqlite
brew swfmill
brew tree
brew unixodbc
brew vim
brew webp
brew wget
brew wxmac
brew x264
brew xmlsh
brew xvid
brew xz
brew zlib

# App Store applications
appstore 1Password
appstore CloudApp
appstore Coda 2
appstore Day One
appstore Evernote
appstore GarageBand
appstore Growl
appstore Hype
appstore iA Writer
appstore iBooks Author
appstore iMovie
appstore iPhoto
appstore Keynote
appstore Kobito
appstore LINE
appstore MindNode Pro
appstore MultiMarkdown Composer
appstore Numbers
appstore OneDrive
appstore Pages
appstore Pixelmator
appstore Pocket
appstore QREncoder
appstore Skitch
appstore SoundCloud
appstore StuffIt Expander
appstore Twitter
appstore Xcode
